const createError = require('../utils/createError')

const saveProduct = (req,res,next) => {
    try{

    }catch(e){
        next(e)
    }
}

module.exports = {
    saveProduct
}